environment:
  matrix:
    - GENERATOR: Visual Studio 14 2015 Win64
    - GENERATOR: Visual Studio 14 2015
    - GENERATOR: Visual Studio 12 2013 Win64
    # - GENERATOR: Visual Studio 11 2012
    # - GENERATOR: Visual Studio 10 2010 Win64
    # - GENERATOR: Visual Studio 9 2008

branches:
  except:
    - /^(wip\/)?(travis|osx|ipp)(\-.+)?$/
    - /^master$/

before_build:
  - ps: |
      git submodule -q update --init --recursive
      cd tests
      mkdir build
      cd build
      cmake -G "$env:GENERATOR" .. -DENABLE_AGGRESSIVE_WARNINGS=yes

build_script:
  - ps: |
      cmake --build . --config Debug

test_script:
  - ps: |
      ctest --output-on-failure --interactive-debug-mode 0 -C Debug -V
